#!/bin/bash
# For GCC configurations please look at crosstool-ng-config

# The vendor part has to be changed also in the crosstool-ng-config file
TUPLE=$MACHINE-osquery-linux-gnu

ZLIB_VER="1.3.1"
ZLIB_URL="https://zlib.net/fossils/zlib-${ZLIB_VER}.tar.gz"
ZLIB_SHA="9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"

LLVM_VERSION="18.1.8"
GCC_VERSION="13.4.0" # Notice: this has to match the same version that has been configured in crosstool-ng-config

PARALLEL_JOBS=$(( $(nproc)+1 ))
BUILD_GENERATOR="Ninja"

# Valid values: Release, RelWithDebInfo, MinSizeRel, Debug
LLVM_BUILD_TYPE=MinSizeRel

# If this is false, only the last stage with the clang compile and the first stage, with crosstool gcc will be kept
KEEP_INTERMEDIATE_STAGES=0
