name: Build Toolchain

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install help2man libtool-bin libncurses-dev ninja-build texinfo xz-utils gawk -y   

      - name: Build
        run: ./build.sh "/opt/osquery-toolchain"

      - name: Archive
        run: |
          cd /opt/osquery-toolchain/final
          mv sysroot osquery-toolchain
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="${GITHUB_SHA}"
          fi
          tar -pcvJf osquery-toolchain-${VERSION}.tar.xz osquery-toolchain

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: osquery-toolchain
          path: /opt/osquery-toolchain/osquery-toolchain-*.tar.xz
          
